# Generated by Django 3.2.7 on 2021-09-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanger',
            old_name='date',
            new_name='created_date',
        ),
    ]
