# Generated by Django 3.2.7 on 2021-09-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_rename_date_exchanger_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchanger',
            options={'verbose_name': 'Обменник', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='exchanger',
            name='amount',
        ),
    ]
