# Generated by Django 3.2.7 on 2021-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0003_auto_20210916_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchanger',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='exchanger',
            name='created_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
